version: '3.8'

services:
  backend:
    build: ./backend
    container_name: elevator-simulation-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: elevator-simulation-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped